a = input("Digite algo: ")
print(f"O tipo primitivo desse valor é: {type(a)}")
print(f"Só tem espaço? {a.isspace()}")
print(f"É um número? {a.isnumeric()}")
print(f"É alfabetico? {a.isalpha()}")
print(f"É alfanúmerico? {a.isalnum()}")
print(f"Está em maiúsculas? {a.isupper()}")
print(f"Está em minúsculas? {a.islower()}")
print(f"Está capitalizado? {a.istitle()}")
