print("°"*20)
print(f"{"LUCARS ALUGUEIS":^20}")
print("°"*20)
dia = int(input("Por quantos dias alugado? "))
km = float(input("Quantos km rodado? "))
print('=-'*30)
print(f"Diaria R$:60,00 x {dia} dias = R$:{60*dia:.2f}")
print(f"Km rodado R$:0,15 x {km:.2f}Km = R$:{0.15*km:.2f}")
print(f"Total a pagar R$:{dia*60+km*0.15:.2f}")
